### ISSUE TITLE
项目启动起来后，在googel浏览器访问报错

### ISSUE THREAD

**Issue by gjung126** [bailicangdu/node-elm#103]
C:\D\work\node-elm>npm run dev

> node-elm@1.0.0 dev C:\D\work\node-elm
> cross-env NODE_ENV=development supervisor --harmony index.js

Running node-supervisor with
  program '--harmony index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node --harmony index.js'
Watching directory 'C:\D\work\node-elm' for changes.
Press rs for restarting the process.
连接数据库成功
获取用户信息的参数user_id无效 null
获取用户信息的参数user_id无效 null
获取用户信息的参数user_id无效 null
获取用户信息的参数user_id无效 null
获取用户信息的参数user_id无效 null

**Comment by bailicangdu** [comment]
这是警告，可以忽略

**Comment by luchaoqun125** [comment]
ludaxiongdeMacBook-Pro:node-elm ludaxiong$ npm run dev

> node-elm@1.0.0 dev /Users/ludaxiong/Desktop/my-learn/node-elm
> cross-env NODE_ENV=development supervisor --harmony index.js


Running node-supervisor with
  program '--harmony index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node --harmony index.js'
Watching directory '/Users/ludaxiong/Desktop/my-learn/node-elm' for changes.
Press rs for restarting the process.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/Users/ludaxiong/Desktop/my-learn/node-elm/node_modules/_express@4.16.3@express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/ludaxiong/Desktop/my-learn/node-elm/app.js:72:5)
    at Module._compile (module.js:652:30)
    at loader (/Users/ludaxiong/Desktop/my-learn/node-elm/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ludaxiong/Desktop/my-learn/node-elm/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ludaxiong/Desktop/my-learn/node-elm/index.js:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
Program node --harmony index.js exited with code 1
