### ISSUE TITLE
下载后台项目运行npm run local有报错

### ISSUE THREAD

**Issue by wsz7777** [bailicangdu/node-elm#106]
config-lite load `local` failed
Error: Cannot find module 'local' from '/home/syl/bs/node-elm/mongodb'
    at Function.module.exports [as sync] (/home/syl/bs/node-elm/node_modules/resolve/lib/sync.js:33:11)
    at loadConfig (/home/syl/bs/node-elm/node_modules/config-lite/index.js:37:26)
    at Object.<anonymous> (/home/syl/bs/node-elm/node_modules/config-lite/index.js:22:22)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/syl/bs/node-elm/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/syl/bs/node-elm/mongodb/db.js:4:1)
    at Module._compile (module.js:652:30)
    at loader (/home/syl/bs/node-elm/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/syl/bs/node-elm/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)

**Comment by bailicangdu** [comment]
先开启mongodb，如果没有装的话，可以去官网下载

**Comment by bailicangdu** [comment]
而且不建议执行 run local，这是我在服务器测试用的命令，需要配置local.js文件，平常开发执行 run dev即可

**Comment by wsz7777** [comment]
mdb装了，那这三个项目有什么关联呢？或者说可以分别npm run dev 启动吗？

**Comment by wsz7777** [comment]
local.js是哪个文件啊

**Comment by wsz7777** [comment]
现在清楚了，这三个项目分别启动即可，通过url相连。比较白，勿怪
