### ISSUE TITLE
在本地环境上 添加商铺或者商铺的时候，需要清除缓存并硬性加载页面 页面数据才会更新出来，这是什么原因呢~

### ISSUE THREAD

**Issue by urmax** [bailicangdu/node-elm#169]
在本地环境上 添加商铺或者商铺的时候，需要清除缓存并硬性加载页面 页面数据才会更新出来，这是什么原因呢~

**Comment by urmax** [comment]
keep-alive

**Comment by leoneeec** [comment]
你好想问下本地环境下部署这样报错怎么解决

Error [MongoError]: Unsupported OP_QUERY command: listIndexes. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
    at Function.MongoError.create (D:\Desktop\node-elm\node_modules\mongoose\node_modules\mongodb-core\lib\error.js:31:11)
    at queryCallback (D:\Desktop\node-elm\node_modules\mongoose\node_modules\mongodb-core\lib\cursor.js:212:36)
    at D:\Desktop\node-elm\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:469:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  ok: 0,
  errmsg: 'Unsupported OP_QUERY command: listIndexes. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal',
  code: 352,
  codeName: 'UnsupportedOpQueryCommand'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by urmax** [comment]
您好，感谢您的来信，邮件我已收到，我会尽快回复给您。谢谢！

**Comment by longmore** [comment]
张荣谋收到，谢谢！

**Comment by lxh666666** [comment]
请问是什么原因呢 我也遇到啦

**Comment by urmax** [comment]
您好，感谢您的来信，邮件我已收到，我会尽快回复给您。谢谢！
