### ISSUE TITLE
配置出错

### ISSUE THREAD

**Issue by tomoat** [bailicangdu/node-elm#45]
```sh
/Users/tomato/Sites/vue-test/node-elm/app.js:72
  name: _configLite2.default.session.name,
                                    ^

TypeError: Cannot read property 'name' of undefined
    at Object.<anonymous> (/Users/tomato/Sites/vue-test/node-elm/app.js:33:11)
    at Module._compile (module.js:573:30)
    at loader (/Users/tomato/Sites/vue-test/node-elm/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tomato/Sites/vue-test/node-elm/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tomato/Sites/vue-test/node-elm/index.js:2:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

建议尽量使用一种模块加载方式，配置文件使用module.exports的Commonjs模块加载方式,其他代码多半有使用ES7的模块加载方式

**Comment by tomoat** [comment]
全部是使用export default config 这样的话，就不需要额外的多安装一个config-lite模块了吧
