### ISSUE TITLE
npm run local 报错

### ISSUE THREAD

**Issue by doubleTotoo** [bailicangdu/node-elm#64]
config-lite load `local` failed
Error: Cannot find module 'local' from 'E:\workSpace\node-elm2\node-elm'
    at Function.module.exports [as sync] (E:\workSpace\node-elm2\node-elm\node_modules\_resolve@1.1.7@resolve\lib\sync.js:33:11)
    at loadConfig (E:\workSpace\node-elm2\node-elm\node_modules\_config-lite@1.6.0@config-lite\index.js:37:26)
    at Object.<anonymous> (E:\workSpace\node-elm2\node-elm\node_modules\_config-lite@1.6.0@config-lite\index.js:22:22)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\workSpace\node-elm2\node-elm\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)

**Comment by doubleTotoo** [comment]
![image](https://user-images.githubusercontent.com/21987324/33256033-395fec00-d38b-11e7-9923-5bf0a8d0a629.png) 添加 local.js 可以解决报错

**Comment by bailicangdu** [comment]
好奇怪的问题

**Comment by bailicangdu** [comment]
npm run local 是我在服务器端测试用的命令，local.js涉及服务器数据库的账户密码，所以没上传，你们一般也用不上
