### ISSUE TITLE
npm run dev 报错(node:6.10.2)

### ISSUE THREAD

**Issue by wangyeli** [bailicangdu/node-elm#70]
> node-elm@1.0.0 dev /home/wang/serverWeb/node-elm
> cross-env NODE_ENV=development supervisor --harmony index.js

Running node-supervisor with
  program '--harmony index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node --harmony index.js'
Watching directory '/home/wang/serverWeb/node-elm' for changes.
Press rs for restarting the process.
/home/wang/serverWeb/node-elm/app.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wang/serverWeb/node-elm/index.js:2:1)
Program node --harmony index.js exited with code 1

Starting child process with 'node --harmony index.js'
/home/wang/serverWeb/node-elm/app.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wang/serverWeb/node-elm/index.js:2:1)
Program node --harmony index.js exited with code 1

Starting child process with 'node --harmony index.js'
/home/wang/serverWeb/node-elm/app.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wang/serverWeb/node-elm/index.js:2:1)
Program node --harmony index.js exited with code 1

Starting child process with 'node --harmony index.js'
/home/wang/serverWeb/node-elm/app.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/wang/serverWeb/node-elm/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/wang/serverWeb/node-elm/index.js:2:1)
Program node --harmony index.js exited with code 1

Starting child process with 'node --harmony index.js'
/home/wang/serverWeb/node-elm/app.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';

**Comment by wangyeli** [comment]
win7运行没问题,Mac报错

**Comment by bailicangdu** [comment]
是不是重复启动了
